Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Bootstrap",
            "name": "Bootstrap",
            "summary": "",
            "url": "classes/App-Bootstrap.html"
        },                {
            "fqsen": "\\App\\Bootstrap\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Boot\u0020instace\u0020of\u0020App",
            "url": "classes/App-Bootstrap.html#method_boot"
        },                {
            "fqsen": "\\App\\Bootstrap\u003A\u003AgetEntityManager\u0028\u0029",
            "name": "getEntityManager",
            "summary": "Returns\u0020instance\u0020of\u0020EntityManager",
            "url": "classes/App-Bootstrap.html#method_getEntityManager"
        },                {
            "fqsen": "\\App\\Controller\\App",
            "name": "App",
            "summary": "",
            "url": "classes/App-Controller-App.html"
        },                {
            "fqsen": "\\App\\Controller\\App\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-App.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\App\u003A\u003AcontrollerFactory\u0028\u0029",
            "name": "controllerFactory",
            "summary": "Cretes\u0020instace\u0020of\u0020controller\u0020depends\u0020on\u0020request",
            "url": "classes/App-Controller-App.html#method_controllerFactory"
        },                {
            "fqsen": "\\App\\Controller\\Article",
            "name": "Article",
            "summary": "",
            "url": "classes/App-Controller-Article.html"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-Article.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Gets\u0020all\u0020articles",
            "url": "classes/App-Controller-Article.html#method_getAll"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003AgetOneById\u0028\u0029",
            "name": "getOneById",
            "summary": "Gets\u0020one\u0020article\u0020by\u0020his\u0020ID",
            "url": "classes/App-Controller-Article.html#method_getOneById"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003AgetOneByAlias\u0028\u0029",
            "name": "getOneByAlias",
            "summary": "Gets\u0020one\u0020article\u0020by\u0020his\u0020alias",
            "url": "classes/App-Controller-Article.html#method_getOneByAlias"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020new\u0020article",
            "url": "classes/App-Controller-Article.html#method_create"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Edit\u0020article\u0020by\u0020ID",
            "url": "classes/App-Controller-Article.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\Article\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020article\u0020by\u0020ID",
            "url": "classes/App-Controller-Article.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\Base",
            "name": "Base",
            "summary": "",
            "url": "classes/App-Controller-Base.html"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Controller-Base.html#method___construct"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-Base.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003AregisterDefaultRoutes\u0028\u0029",
            "name": "registerDefaultRoutes",
            "summary": "Register\u0020default\u0020routes",
            "url": "classes/App-Controller-Base.html#method_registerDefaultRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003ArequestDispatch\u0028\u0029",
            "name": "requestDispatch",
            "summary": "Dispatch\u0020request\u0020to\u0020predefined\u0020routes",
            "url": "classes/App-Controller-Base.html#method_requestDispatch"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "Returns\u0020API\u0020state",
            "url": "classes/App-Controller-Base.html#method_getState"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003AsetView\u0028\u0029",
            "name": "setView",
            "summary": "Sets\u0020view",
            "url": "classes/App-Controller-Base.html#method_setView"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003AsetRequest\u0028\u0029",
            "name": "setRequest",
            "summary": "Sets\u0020request",
            "url": "classes/App-Controller-Base.html#method_setRequest"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003AcheckPerms\u0028\u0029",
            "name": "checkPerms",
            "summary": "Checks\u0020user\u0020permitions\u0020on\u0020route\u0020action",
            "url": "classes/App-Controller-Base.html#method_checkPerms"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003A\u0024entityManager",
            "name": "entityManager",
            "summary": "",
            "url": "classes/App-Controller-Base.html#property_entityManager"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003A\u0024queryBuilder",
            "name": "queryBuilder",
            "summary": "",
            "url": "classes/App-Controller-Base.html#property_queryBuilder"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003A\u0024view",
            "name": "view",
            "summary": "",
            "url": "classes/App-Controller-Base.html#property_view"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003A\u0024request",
            "name": "request",
            "summary": "",
            "url": "classes/App-Controller-Base.html#property_request"
        },                {
            "fqsen": "\\App\\Controller\\Base\u003A\u003A\u0024router",
            "name": "router",
            "summary": "",
            "url": "classes/App-Controller-Base.html#property_router"
        },                {
            "fqsen": "\\App\\Controller\\File",
            "name": "File",
            "summary": "",
            "url": "classes/App-Controller-File.html"
        },                {
            "fqsen": "\\App\\Controller\\File\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-File.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\File\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Gets\u0020all\u0020files",
            "url": "classes/App-Controller-File.html#method_getAll"
        },                {
            "fqsen": "\\App\\Controller\\File\u003A\u003AgetOneById\u0028\u0029",
            "name": "getOneById",
            "summary": "Gets\u0020one\u0020file\u0020by\u0020ID",
            "url": "classes/App-Controller-File.html#method_getOneById"
        },                {
            "fqsen": "\\App\\Controller\\File\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Uploads\u0020file\u0020to\u0020storage",
            "url": "classes/App-Controller-File.html#method_upload"
        },                {
            "fqsen": "\\App\\Controller\\Gallery",
            "name": "Gallery",
            "summary": "",
            "url": "classes/App-Controller-Gallery.html"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-Gallery.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Gets\u0020all\u0020galleries",
            "url": "classes/App-Controller-Gallery.html#method_getAll"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003AgetOneById\u0028\u0029",
            "name": "getOneById",
            "summary": "Gets\u0020one\u0020gallery\u0020by\u0020ID",
            "url": "classes/App-Controller-Gallery.html#method_getOneById"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003AgetOneByAlias\u0028\u0029",
            "name": "getOneByAlias",
            "summary": "Gets\u0020one\u0020gallery\u0020by\u0020alias",
            "url": "classes/App-Controller-Gallery.html#method_getOneByAlias"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "Find\u0020galleries\u0020by\u0020key\u0020and\u0020value",
            "url": "classes/App-Controller-Gallery.html#method_find"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020new\u0020gallery",
            "url": "classes/App-Controller-Gallery.html#method_create"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Edit\u0020gallery\u0020by\u0020ID",
            "url": "classes/App-Controller-Gallery.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\Gallery\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020galery\u0020by\u0020ID",
            "url": "classes/App-Controller-Gallery.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\IBase",
            "name": "IBase",
            "summary": "",
            "url": "classes/App-Controller-IBase.html"
        },                {
            "fqsen": "\\App\\Controller\\IBase\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "",
            "url": "classes/App-Controller-IBase.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Image",
            "name": "Image",
            "summary": "",
            "url": "classes/App-Controller-Image.html"
        },                {
            "fqsen": "\\App\\Controller\\Image\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-Image.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Image\u003A\u003AgetOneById\u0028\u0029",
            "name": "getOneById",
            "summary": "Gets\u0020one\u0020image\u0020by\u0020ID",
            "url": "classes/App-Controller-Image.html#method_getOneById"
        },                {
            "fqsen": "\\App\\Controller\\Image\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Creates\u0020new\u0020image",
            "url": "classes/App-Controller-Image.html#method_upload"
        },                {
            "fqsen": "\\App\\Controller\\Image\u003A\u003Aedit\u0028\u0029",
            "name": "edit",
            "summary": "Edits\u0020image\u0020by\u0020ID",
            "url": "classes/App-Controller-Image.html#method_edit"
        },                {
            "fqsen": "\\App\\Controller\\Image\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Deletes\u0020image\u0020by\u0020ID",
            "url": "classes/App-Controller-Image.html#method_delete"
        },                {
            "fqsen": "\\App\\Controller\\Image\u003A\u003ATHUMBNAIL_DIMENSIONS",
            "name": "THUMBNAIL_DIMENSIONS",
            "summary": "",
            "url": "classes/App-Controller-Image.html#constant_THUMBNAIL_DIMENSIONS"
        },                {
            "fqsen": "\\App\\Controller\\Mail",
            "name": "Mail",
            "summary": "",
            "url": "classes/App-Controller-Mail.html"
        },                {
            "fqsen": "\\App\\Controller\\Mail\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-Mail.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\Mail\u003A\u003AsendMail\u0028\u0029",
            "name": "sendMail",
            "summary": "Send\u0020Mail",
            "url": "classes/App-Controller-Mail.html#method_sendMail"
        },                {
            "fqsen": "\\App\\Controller\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Controller-User.html"
        },                {
            "fqsen": "\\App\\Controller\\User\u003A\u003AregisterRoutes\u0028\u0029",
            "name": "registerRoutes",
            "summary": "Register\u0020routes\u0020to\u0020router",
            "url": "classes/App-Controller-User.html#method_registerRoutes"
        },                {
            "fqsen": "\\App\\Controller\\User\u003A\u003AgetAll\u0028\u0029",
            "name": "getAll",
            "summary": "Returns\u0020all\u0020users",
            "url": "classes/App-Controller-User.html#method_getAll"
        },                {
            "fqsen": "\\App\\Controller\\User\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Creates\u0020new\u0020user",
            "url": "classes/App-Controller-User.html#method_create"
        },                {
            "fqsen": "\\App\\Controller\\User\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Verifi\u0020user\u0020credentials",
            "url": "classes/App-Controller-User.html#method_login"
        },                {
            "fqsen": "\\App\\Lib\\Assert\\Text",
            "name": "Text",
            "summary": "",
            "url": "classes/App-Lib-Assert-Text.html"
        },                {
            "fqsen": "\\App\\Lib\\Assert\\Text\u003A\u003AisEmail\u0028\u0029",
            "name": "isEmail",
            "summary": "Test\u0020string\u0020for\u0020email\u0020address",
            "url": "classes/App-Lib-Assert-Text.html#method_isEmail"
        },                {
            "fqsen": "\\App\\Lib\\Assert\\Text\u003A\u003AhasMax\u0028\u0029",
            "name": "hasMax",
            "summary": "Test\u0020string\u0020for\u0020max\u0020length",
            "url": "classes/App-Lib-Assert-Text.html#method_hasMax"
        },                {
            "fqsen": "\\App\\Lib\\Assert\\Text\u003A\u003AhasMin\u0028\u0029",
            "name": "hasMin",
            "summary": "Test\u0020string\u0020for\u0020min\u0020length",
            "url": "classes/App-Lib-Assert-Text.html#method_hasMin"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\AuthorizationFactory",
            "name": "AuthorizationFactory",
            "summary": "",
            "url": "classes/App-Lib-Authorization-AuthorizationFactory.html"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\AuthorizationFactory\u003A\u003AfromType\u0028\u0029",
            "name": "fromType",
            "summary": "Creates\u0020authorization\u0020service\u0020by\u0020proidet\u0020type",
            "url": "classes/App-Lib-Authorization-AuthorizationFactory.html#method_fromType"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Base",
            "name": "Base",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Base.html"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Base\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Base.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Base\u003A\u003A\u0024configuration",
            "name": "configuration",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Base.html#property_configuration"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Jwt",
            "name": "Jwt",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Jwt.html"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Jwt\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Jwt.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Jwt\u003A\u003AgetToken\u0028\u0029",
            "name": "getToken",
            "summary": "Returns\u0020JWT",
            "url": "classes/App-Lib-Authorization-Jwt.html#method_getToken"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Jwt\u003A\u003Aauthorize\u0028\u0029",
            "name": "authorize",
            "summary": "Authorize\u0020providet\u0020JWT",
            "url": "classes/App-Lib-Authorization-Jwt.html#method_authorize"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Jwt\u003A\u003ASERVER_NAME",
            "name": "SERVER_NAME",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Jwt.html#constant_SERVER_NAME"
        },                {
            "fqsen": "\\App\\Lib\\Authorization\\Jwt\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/App-Lib-Authorization-Jwt.html#property_key"
        },                {
            "fqsen": "\\App\\Lib\\Command\\AppPasswordCommand",
            "name": "AppPasswordCommand",
            "summary": "",
            "url": "classes/App-Lib-Command-AppPasswordCommand.html"
        },                {
            "fqsen": "\\App\\Lib\\Command\\AppPasswordCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "Command\u0020configuration",
            "url": "classes/App-Lib-Command-AppPasswordCommand.html#method_configure"
        },                {
            "fqsen": "\\App\\Lib\\Command\\AppPasswordCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020command",
            "url": "classes/App-Lib-Command-AppPasswordCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Lib\\Command\\AppPasswordCommand\u003A\u003A\u0024defaultName",
            "name": "defaultName",
            "summary": "",
            "url": "classes/App-Lib-Command-AppPasswordCommand.html#property_defaultName"
        },                {
            "fqsen": "\\App\\Lib\\Command\\FixturesLoadCommand",
            "name": "FixturesLoadCommand",
            "summary": "",
            "url": "classes/App-Lib-Command-FixturesLoadCommand.html"
        },                {
            "fqsen": "\\App\\Lib\\Command\\FixturesLoadCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "Command\u0020configuration",
            "url": "classes/App-Lib-Command-FixturesLoadCommand.html#method_configure"
        },                {
            "fqsen": "\\App\\Lib\\Command\\FixturesLoadCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020command",
            "url": "classes/App-Lib-Command-FixturesLoadCommand.html#method_execute"
        },                {
            "fqsen": "\\App\\Lib\\Command\\FixturesLoadCommand\u003A\u003A\u0024defaultName",
            "name": "defaultName",
            "summary": "",
            "url": "classes/App-Lib-Command-FixturesLoadCommand.html#property_defaultName"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration",
            "name": "Configuration",
            "summary": "",
            "url": "classes/App-Lib-Configuration-Configuration.html"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Configuration-Configuration.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003AparseIniFile\u0028\u0029",
            "name": "parseIniFile",
            "summary": "Parses\u0020ini\u0020file",
            "url": "classes/App-Lib-Configuration-Configuration.html#method_parseIniFile"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003AgetSegment\u0028\u0029",
            "name": "getSegment",
            "summary": "Returns\u0020segment\u0020form\u0020configuration\u0020file",
            "url": "classes/App-Lib-Configuration-Configuration.html#method_getSegment"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020configuration\u0020by\u0020providet\u0020key",
            "url": "classes/App-Lib-Configuration-Configuration.html#method_get"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003AsetSegment\u0028\u0029",
            "name": "setSegment",
            "summary": "Sets\u0020default\u0020segment",
            "url": "classes/App-Lib-Configuration-Configuration.html#method_setSegment"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003A\u0024configuration",
            "name": "configuration",
            "summary": "",
            "url": "classes/App-Lib-Configuration-Configuration.html#property_configuration"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\Configuration\u003A\u003A\u0024segment",
            "name": "segment",
            "summary": "",
            "url": "classes/App-Lib-Configuration-Configuration.html#property_segment"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\ConfigurationFactory",
            "name": "ConfigurationFactory",
            "summary": "",
            "url": "classes/App-Lib-Configuration-ConfigurationFactory.html"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\ConfigurationFactory\u003A\u003AfromFileName\u0028\u0029",
            "name": "fromFileName",
            "summary": "Creates\u0020configuration\u0020from\u0020filename",
            "url": "classes/App-Lib-Configuration-ConfigurationFactory.html#method_fromFileName"
        },                {
            "fqsen": "\\App\\Lib\\Configuration\\ConfigurationFactory\u003A\u003ACONFIG_DIRECTORY",
            "name": "CONFIG_DIRECTORY",
            "summary": "",
            "url": "classes/App-Lib-Configuration-ConfigurationFactory.html#constant_CONFIG_DIRECTORY"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File",
            "name": "File",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AsetPath\u0028\u0029",
            "name": "setPath",
            "summary": "Sets\u0020file\u0020path",
            "url": "classes/App-Lib-FileSystem-File.html#method_setPath"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AsetMimeType\u0028\u0029",
            "name": "setMimeType",
            "summary": "Sets\u0020mime\u0020type",
            "url": "classes/App-Lib-FileSystem-File.html#method_setMimeType"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AsetPermitions\u0028\u0029",
            "name": "setPermitions",
            "summary": "Sets\u0020file\u0020permitions",
            "url": "classes/App-Lib-FileSystem-File.html#method_setPermitions"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AsetUploadName\u0028\u0029",
            "name": "setUploadName",
            "summary": "Sets\u0020upload\u0020name",
            "url": "classes/App-Lib-FileSystem-File.html#method_setUploadName"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AsetExtension\u0028\u0029",
            "name": "setExtension",
            "summary": "Set\u0020file\u0020extension",
            "url": "classes/App-Lib-FileSystem-File.html#method_setExtension"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AmimeTypeToExtension\u0028\u0029",
            "name": "mimeTypeToExtension",
            "summary": "Mime\u0020to\u0020extension",
            "url": "classes/App-Lib-FileSystem-File.html#method_mimeTypeToExtension"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AgetFilename\u0028\u0029",
            "name": "getFilename",
            "summary": "Returns\u0020filename",
            "url": "classes/App-Lib-FileSystem-File.html#method_getFilename"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AgetBasename\u0028\u0029",
            "name": "getBasename",
            "summary": "Returns\u0020basename",
            "url": "classes/App-Lib-FileSystem-File.html#method_getBasename"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Returns\u0020path",
            "url": "classes/App-Lib-FileSystem-File.html#method_getPath"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AgetDirname\u0028\u0029",
            "name": "getDirname",
            "summary": "Returns\u0020directory",
            "url": "classes/App-Lib-FileSystem-File.html#method_getDirname"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AgetUploadName\u0028\u0029",
            "name": "getUploadName",
            "summary": "Returns\u0020upload\u0020name",
            "url": "classes/App-Lib-FileSystem-File.html#method_getUploadName"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AgetMimeType\u0028\u0029",
            "name": "getMimeType",
            "summary": "Return\u0020file\u0020mime\u0020type",
            "url": "classes/App-Lib-FileSystem-File.html#method_getMimeType"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AisImage\u0028\u0029",
            "name": "isImage",
            "summary": "Checks\u0020if\u0020file\u0020is\u0020image",
            "url": "classes/App-Lib-FileSystem-File.html#method_isImage"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AtoImage\u0028\u0029",
            "name": "toImage",
            "summary": "Creates\u0020image\u0020from\u0020file",
            "url": "classes/App-Lib-FileSystem-File.html#method_toImage"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003Amove\u0028\u0029",
            "name": "move",
            "summary": "Moves\u0020file\u0020to\u0020new\u0020location",
            "url": "classes/App-Lib-FileSystem-File.html#method_move"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003Arename\u0028\u0029",
            "name": "rename",
            "summary": "Rename\u0020file",
            "url": "classes/App-Lib-FileSystem-File.html#method_rename"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003Acopy\u0028\u0029",
            "name": "copy",
            "summary": "Copy\u0020file\u0020to\u0020destination",
            "url": "classes/App-Lib-FileSystem-File.html#method_copy"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003Aclone\u0028\u0029",
            "name": "clone",
            "summary": "Clone\u0020file",
            "url": "classes/App-Lib-FileSystem-File.html#method_clone"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Delete\u0020file",
            "url": "classes/App-Lib-FileSystem-File.html#method_delete"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003AMIME_TYPES",
            "name": "MIME_TYPES",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#constant_MIME_TYPES"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#property_path"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A\u0024dirname",
            "name": "dirname",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#property_dirname"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A\u0024filename",
            "name": "filename",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#property_filename"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A\u0024mimeType",
            "name": "mimeType",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#property_mimeType"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A\u0024extension",
            "name": "extension",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#property_extension"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\File\u003A\u003A\u0024uploadName",
            "name": "uploadName",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-File.html#property_uploadName"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem",
            "name": "FileSystem",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-FileSystem.html"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003Aopen\u0028\u0029",
            "name": "open",
            "summary": "Open\u0020file\u0020in\u0020file\u0020system",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#method_open"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003Aupload\u0028\u0029",
            "name": "upload",
            "summary": "Uploads\u0020file\u0020to\u0020web\u0020storage",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#method_upload"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "Returns\u0020uri\u0020to\u0020file",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#method_getUri"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003AisAbsolute\u0028\u0029",
            "name": "isAbsolute",
            "summary": "Check\u0020if\u0020path\u0020is\u0020absolute",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#method_isAbsolute"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003ASTORAGE",
            "name": "STORAGE",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#constant_STORAGE"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003ASTORAGE_NAME",
            "name": "STORAGE_NAME",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#constant_STORAGE_NAME"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003APUBLIC_DIRECTORY",
            "name": "PUBLIC_DIRECTORY",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#constant_PUBLIC_DIRECTORY"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\FileSystem\u003A\u003AIMAGES_DIRECTORY",
            "name": "IMAGES_DIRECTORY",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-FileSystem.html#constant_IMAGES_DIRECTORY"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image",
            "name": "Image",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-Image.html"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-Image.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-Image.html#method___destruct"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saves\u0020image",
            "url": "classes/App-Lib-FileSystem-Image.html#method_save"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003AsaveAs\u0028\u0029",
            "name": "saveAs",
            "summary": "Saves\u0020image\u0020as",
            "url": "classes/App-Lib-FileSystem-Image.html#method_saveAs"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003AsetQuality\u0028\u0029",
            "name": "setQuality",
            "summary": "Change\u0020quality\u0020of\u0020jpeg",
            "url": "classes/App-Lib-FileSystem-Image.html#method_setQuality"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003AsetFormat\u0028\u0029",
            "name": "setFormat",
            "summary": "Sets\u0020image\u0020format",
            "url": "classes/App-Lib-FileSystem-Image.html#method_setFormat"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Resizes\u0020image",
            "url": "classes/App-Lib-FileSystem-Image.html#method_resize"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003AgenerateThumbnails\u0028\u0029",
            "name": "generateThumbnails",
            "summary": "Return\u0020thumbnail\u0020sources",
            "url": "classes/App-Lib-FileSystem-Image.html#method_generateThumbnails"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003AFORMAT",
            "name": "FORMAT",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-Image.html#constant_FORMAT"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003AMIME_TYPES",
            "name": "MIME_TYPES",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-Image.html#constant_MIME_TYPES"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem\\Image\u003A\u003A\u0024image",
            "name": "image",
            "summary": "",
            "url": "classes/App-Lib-FileSystem-Image.html#property_image"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body",
            "name": "Body",
            "summary": "",
            "url": "classes/App-Lib-Http-Body.html"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Http-Body.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AsetBody\u0028\u0029",
            "name": "setBody",
            "summary": "Parse\u0020request\u0020body",
            "url": "classes/App-Lib-Http-Body.html#method_setBody"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AsetContentType\u0028\u0029",
            "name": "setContentType",
            "summary": "Sets\u0020request\u0020content\u0020type",
            "url": "classes/App-Lib-Http-Body.html#method_setContentType"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AsetFiles\u0028\u0029",
            "name": "setFiles",
            "summary": "Sets\u0020request\u0020files\u0020to\u0020instance",
            "url": "classes/App-Lib-Http-Body.html#method_setFiles"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020requests\u0020body",
            "url": "classes/App-Lib-Http-Body.html#method_getBody"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AgetBodyData\u0028\u0029",
            "name": "getBodyData",
            "summary": "Returns\u0020body\u0020data\u0020by\u0020key",
            "url": "classes/App-Lib-Http-Body.html#method_getBodyData"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AgetContentType\u0028\u0029",
            "name": "getContentType",
            "summary": "Returns\u0020body\u0020content\u0020type",
            "url": "classes/App-Lib-Http-Body.html#method_getContentType"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003AgetFiles\u0028\u0029",
            "name": "getFiles",
            "summary": "Returns\u0020files",
            "url": "classes/App-Lib-Http-Body.html#method_getFiles"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003A\u0024contentType",
            "name": "contentType",
            "summary": "",
            "url": "classes/App-Lib-Http-Body.html#property_contentType"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/App-Lib-Http-Body.html#property_body"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Body\u003A\u003A\u0024files",
            "name": "files",
            "summary": "",
            "url": "classes/App-Lib-Http-Body.html#property_files"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request",
            "name": "Request",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020instance\u0020of\u0020Request\u0020class.",
            "url": "classes/App-Lib-Http-Request.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AsetMethod\u0028\u0029",
            "name": "setMethod",
            "summary": "Sets\u0020request\u0020method",
            "url": "classes/App-Lib-Http-Request.html#method_setMethod"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "Returns\u0020requests\u0020URI",
            "url": "classes/App-Lib-Http-Request.html#method_getUri"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AgetAuthorization\u0028\u0029",
            "name": "getAuthorization",
            "summary": "Returns\u0020api\u0020key\u0020from\u0020request\u0020header",
            "url": "classes/App-Lib-Http-Request.html#method_getAuthorization"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020requests\u0020body.",
            "url": "classes/App-Lib-Http-Request.html#method_getBody"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "Returns\u0020request\u0020method",
            "url": "classes/App-Lib-Http-Request.html#method_getMethod"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AsetAccept\u0028\u0029",
            "name": "setAccept",
            "summary": "Sets\u0020accept\u0020format",
            "url": "classes/App-Lib-Http-Request.html#method_setAccept"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AgetAccept\u0028\u0029",
            "name": "getAccept",
            "summary": "Returns\u0020request\u0020accept",
            "url": "classes/App-Lib-Http-Request.html#method_getAccept"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003AgetResource\u0028\u0029",
            "name": "getResource",
            "summary": "Retruns\u0020request\u0020resource",
            "url": "classes/App-Lib-Http-Request.html#method_getResource"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024isSecured",
            "name": "isSecured",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_isSecured"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024method",
            "name": "method",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_method"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024uri",
            "name": "uri",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_uri"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024authorization",
            "name": "authorization",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_authorization"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024body",
            "name": "body",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_body"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024remoteAddress",
            "name": "remoteAddress",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_remoteAddress"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Request\u003A\u003A\u0024accept",
            "name": "accept",
            "summary": "",
            "url": "classes/App-Lib-Http-Request.html#property_accept"
        },                {
            "fqsen": "\\App\\Lib\\Http\\RequestFactory",
            "name": "RequestFactory",
            "summary": "",
            "url": "classes/App-Lib-Http-RequestFactory.html"
        },                {
            "fqsen": "\\App\\Lib\\Http\\RequestFactory\u003A\u003AgetUri\u0028\u0029",
            "name": "getUri",
            "summary": "Returns\u0020new\u0020instance\u0020of\u0020Uri\u0020class\u0020by\u0020URI",
            "url": "classes/App-Lib-Http-RequestFactory.html#method_getUri"
        },                {
            "fqsen": "\\App\\Lib\\Http\\RequestFactory\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Returns\u0020new\u0020instance\u0020of\u0020Body\u0020class",
            "url": "classes/App-Lib-Http-RequestFactory.html#method_getBody"
        },                {
            "fqsen": "\\App\\Lib\\Http\\RequestFactory\u003A\u003AfromGlobals\u0028\u0029",
            "name": "fromGlobals",
            "summary": "Returns\u0020new\u0020instance\u0020of\u0020Request\u0020class\u0020from\u0020server\u0020globals",
            "url": "classes/App-Lib-Http-RequestFactory.html#method_fromGlobals"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Uri",
            "name": "Uri",
            "summary": "",
            "url": "classes/App-Lib-Http-Uri.html"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Uri\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Http-Uri.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Uri\u003A\u003AsetPath\u0028\u0029",
            "name": "setPath",
            "summary": "Sets\u0020path",
            "url": "classes/App-Lib-Http-Uri.html#method_setPath"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Uri\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Returns\u0020path",
            "url": "classes/App-Lib-Http-Uri.html#method_getPath"
        },                {
            "fqsen": "\\App\\Lib\\Http\\Uri\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/App-Lib-Http-Uri.html#property_path"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers",
            "name": "Headers",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Headers.html"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Headers.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "Set\u0020single\u0020header",
            "url": "classes/App-Lib-Mailer-Headers.html#method_setHeader"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003AgetHeader\u0028\u0029",
            "name": "getHeader",
            "summary": "Get\u0020single\u0020header",
            "url": "classes/App-Lib-Mailer-Headers.html#method_getHeader"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "Return\u0020string\u0020header\u0020for\u0020email",
            "url": "classes/App-Lib-Mailer-Headers.html#method_getHeaders"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003AaddBcc\u0028\u0029",
            "name": "addBcc",
            "summary": "Adds\u0020Bcc\u0020to\u0020headders",
            "url": "classes/App-Lib-Mailer-Headers.html#method_addBcc"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003AsetFrom\u0028\u0029",
            "name": "setFrom",
            "summary": "Adds\u0020From\u0020to\u0020headders",
            "url": "classes/App-Lib-Mailer-Headers.html#method_setFrom"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Headers\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Headers.html#property_headers"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail",
            "name": "Mail",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Mail.html"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Mail.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003AsetTo\u0028\u0029",
            "name": "setTo",
            "summary": "Set\u0020Recipient\u0027s\u0020email",
            "url": "classes/App-Lib-Mailer-Mail.html#method_setTo"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003AsetFrom\u0028\u0029",
            "name": "setFrom",
            "summary": "Set\u0020Sender\u0027s\u0020email",
            "url": "classes/App-Lib-Mailer-Mail.html#method_setFrom"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003AsetSubject\u0028\u0029",
            "name": "setSubject",
            "summary": "Set\u0020Subject",
            "url": "classes/App-Lib-Mailer-Mail.html#method_setSubject"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Set\u0020Content",
            "url": "classes/App-Lib-Mailer-Mail.html#method_setContent"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003AaddBcc\u0028\u0029",
            "name": "addBcc",
            "summary": "Add\u0020hidden\u0020copy",
            "url": "classes/App-Lib-Mailer-Mail.html#method_addBcc"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "Send\u0020mail",
            "url": "classes/App-Lib-Mailer-Mail.html#method_send"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003A\u0024to",
            "name": "to",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Mail.html#property_to"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003A\u0024subject",
            "name": "subject",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Mail.html#property_subject"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Mail.html#property_content"
        },                {
            "fqsen": "\\App\\Lib\\Mailer\\Mail\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/App-Lib-Mailer-Mail.html#property_headers"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route",
            "name": "Route",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020instance\u0020of\u0020Route\u0020class",
            "url": "classes/App-Lib-Middleware-Route.html#method___construct"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "Returns\u0020route\u0020version",
            "url": "classes/App-Lib-Middleware-Route.html#method_getVersion"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "Returns\u0020route\u0020HTTP\u0020method",
            "url": "classes/App-Lib-Middleware-Route.html#method_getMethod"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AgetPattern\u0028\u0029",
            "name": "getPattern",
            "summary": "Returns\u0020regulat\u0020expression\u0020pattern",
            "url": "classes/App-Lib-Middleware-Route.html#method_getPattern"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AgetAction\u0028\u0029",
            "name": "getAction",
            "summary": "Returns\u0020route\u0020action",
            "url": "classes/App-Lib-Middleware-Route.html#method_getAction"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AsetParams\u0028\u0029",
            "name": "setParams",
            "summary": "Sets\u0020route\u0020params",
            "url": "classes/App-Lib-Middleware-Route.html#method_setParams"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AgetParams\u0028\u0029",
            "name": "getParams",
            "summary": "Returns\u0020action\u0020params",
            "url": "classes/App-Lib-Middleware-Route.html#method_getParams"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003AisSecure\u0028\u0029",
            "name": "isSecure",
            "summary": "Returns\u0020secure\u0020route\u0020state",
            "url": "classes/App-Lib-Middleware-Route.html#method_isSecure"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html#property_version"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A\u0024method",
            "name": "method",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html#property_method"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A\u0024pattern",
            "name": "pattern",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html#property_pattern"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A\u0024action",
            "name": "action",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html#property_action"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A\u0024params",
            "name": "params",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html#property_params"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Route\u003A\u003A\u0024secure",
            "name": "secure",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Route.html#property_secure"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\RouteFactory",
            "name": "RouteFactory",
            "summary": "",
            "url": "classes/App-Lib-Middleware-RouteFactory.html"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\RouteFactory\u003A\u003AfromConstants\u0028\u0029",
            "name": "fromConstants",
            "summary": "Creates\u0020route\u0020from\u0020constatns",
            "url": "classes/App-Lib-Middleware-RouteFactory.html#method_fromConstants"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Router",
            "name": "Router",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Router.html"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Router\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020router\u0020HTTP\u0020request.",
            "url": "classes/App-Lib-Middleware-Router.html#method_register"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Router\u003A\u003AgetRoutes\u0028\u0029",
            "name": "getRoutes",
            "summary": "Returns\u0020all\u0020registered\u0020routes.",
            "url": "classes/App-Lib-Middleware-Router.html#method_getRoutes"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Router\u003A\u003Adispatch\u0028\u0029",
            "name": "dispatch",
            "summary": "Dispatch\u0020request\u0020to\u0020predefined\u0020routes.",
            "url": "classes/App-Lib-Middleware-Router.html#method_dispatch"
        },                {
            "fqsen": "\\App\\Lib\\Middleware\\Router\u003A\u003A\u0024routes",
            "name": "routes",
            "summary": "",
            "url": "classes/App-Lib-Middleware-Router.html#property_routes"
        },                {
            "fqsen": "\\App\\Lib\\Security\\Hash",
            "name": "Hash",
            "summary": "",
            "url": "classes/App-Lib-Security-Hash.html"
        },                {
            "fqsen": "\\App\\Lib\\Security\\Hash\u003A\u003AgetPepper\u0028\u0029",
            "name": "getPepper",
            "summary": "Gets\u0020pepper\u0020from\u0020global\u0020domain\u0020config",
            "url": "classes/App-Lib-Security-Hash.html#method_getPepper"
        },                {
            "fqsen": "\\App\\Lib\\Security\\Hash\u003A\u003AhashString\u0028\u0029",
            "name": "hashString",
            "summary": "Basic\u0020hash\u0020for\u0020pepper\u0020and\u0020password\u0020before\u0020submit\/verify",
            "url": "classes/App-Lib-Security-Hash.html#method_hashString"
        },                {
            "fqsen": "\\App\\Lib\\Security\\Hash\u003A\u003AgetHash\u0028\u0029",
            "name": "getHash",
            "summary": "Creates\u0020hash\u0020from\u0020string",
            "url": "classes/App-Lib-Security-Hash.html#method_getHash"
        },                {
            "fqsen": "\\App\\Lib\\Security\\Hash\u003A\u003AverifyHash\u0028\u0029",
            "name": "verifyHash",
            "summary": "Verify\u0020hash\u0020from\u0020string",
            "url": "classes/App-Lib-Security-Hash.html#method_verifyHash"
        },                {
            "fqsen": "\\App\\Lib\\Util\\Cryptography",
            "name": "Cryptography",
            "summary": "",
            "url": "classes/App-Lib-Util-Cryptography.html"
        },                {
            "fqsen": "\\App\\Lib\\Util\\Cryptography\u003A\u003Arandom\u0028\u0029",
            "name": "random",
            "summary": "Generates\u0020random\u0020string",
            "url": "classes/App-Lib-Util-Cryptography.html#method_random"
        },                {
            "fqsen": "\\App\\Lib\\Util\\Cryptography\u003A\u003AhashHmac\u0028\u0029",
            "name": "hashHmac",
            "summary": "Hash\u0020content\u0020by\u0020provided\u0020key",
            "url": "classes/App-Lib-Util-Cryptography.html#method_hashHmac"
        },                {
            "fqsen": "\\App\\Lib\\Util\\Input",
            "name": "Input",
            "summary": "String\u0020tools\u0020library",
            "url": "classes/App-Lib-Util-Input.html"
        },                {
            "fqsen": "\\App\\Lib\\Util\\Input\u003A\u003AtoAscii\u0028\u0029",
            "name": "toAscii",
            "summary": "Converts\u0020input\u0020string\u0020to\u0020ASCII",
            "url": "classes/App-Lib-Util-Input.html#method_toAscii"
        },                {
            "fqsen": "\\App\\Lib\\Util\\Input\u003A\u003AtoAlias\u0028\u0029",
            "name": "toAlias",
            "summary": "Converts\u0020input\u0020string\u0020to\u0020url\u0020like\u0020string",
            "url": "classes/App-Lib-Util-Input.html#method_toAlias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article",
            "name": "Article",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020new\u0020instance\u0020of\u0020Article\u0020class.",
            "url": "classes/App-Model-Entity-Article.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020article\u0020title.",
            "url": "classes/App-Model-Entity-Article.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AsetAlias\u0028\u0029",
            "name": "setAlias",
            "summary": "Sets\u0020article\u0020alias.",
            "url": "classes/App-Model-Entity-Article.html#method_setAlias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AsetContent\u0028\u0029",
            "name": "setContent",
            "summary": "Sets\u0020article\u0020content.",
            "url": "classes/App-Model-Entity-Article.html#method_setContent"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AsetUpdated\u0028\u0029",
            "name": "setUpdated",
            "summary": "Sets\u0020article\u0020updated\u0020date.",
            "url": "classes/App-Model-Entity-Article.html#method_setUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AsetState\u0028\u0029",
            "name": "setState",
            "summary": "Sets\u0020article\u0020state",
            "url": "classes/App-Model-Entity-Article.html#method_setState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Returns\u0020article\u0020ID.",
            "url": "classes/App-Model-Entity-Article.html#method_getId"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Returns\u0020article\u0020title.",
            "url": "classes/App-Model-Entity-Article.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AgetAlias\u0028\u0029",
            "name": "getAlias",
            "summary": "Returns\u0020article\u0020alias.",
            "url": "classes/App-Model-Entity-Article.html#method_getAlias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "Returns\u0020article\u0020content.",
            "url": "classes/App-Model-Entity-Article.html#method_getContent"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AgetUpdated\u0028\u0029",
            "name": "getUpdated",
            "summary": "Returns\u0020article\u0020updated\u0020date.",
            "url": "classes/App-Model-Entity-Article.html#method_getUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "Returns\u0020article\u0020state",
            "url": "classes/App-Model-Entity-Article.html#method_getState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html#property_id"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html#property_title"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A\u0024alias",
            "name": "alias",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html#property_alias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html#property_content"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A\u0024updated",
            "name": "updated",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html#property_updated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Article\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/App-Model-Entity-Article.html#property_state"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File",
            "name": "File",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020file\u0020title",
            "url": "classes/App-Model-Entity-File.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AsetPath\u0028\u0029",
            "name": "setPath",
            "summary": "Sets\u0020path\u0020to\u0020file",
            "url": "classes/App-Model-Entity-File.html#method_setPath"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AsetUpdated\u0028\u0029",
            "name": "setUpdated",
            "summary": "Sets\u0020file\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-File.html#method_setUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AsetState\u0028\u0029",
            "name": "setState",
            "summary": "Sets\u0020file\u0020state",
            "url": "classes/App-Model-Entity-File.html#method_setState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Returns\u0020file\u0020ID",
            "url": "classes/App-Model-Entity-File.html#method_getId"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Returns\u0020file\u0020title",
            "url": "classes/App-Model-Entity-File.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "Returns\u0020file\u0020path",
            "url": "classes/App-Model-Entity-File.html#method_getPath"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AgetUpdated\u0028\u0029",
            "name": "getUpdated",
            "summary": "Returns\u0020file\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-File.html#method_getUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "Returns\u0020file\u0020state",
            "url": "classes/App-Model-Entity-File.html#method_getState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html#property_id"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html#property_title"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003A\u0024path",
            "name": "path",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html#property_path"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003A\u0024updated",
            "name": "updated",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html#property_updated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\File\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/App-Model-Entity-File.html#property_state"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery",
            "name": "Gallery",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020gallery\u0020title",
            "url": "classes/App-Model-Entity-Gallery.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "Sets\u0020gallery\u0020description",
            "url": "classes/App-Model-Entity-Gallery.html#method_setDescription"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AsetAlias\u0028\u0029",
            "name": "setAlias",
            "summary": "Sets\u0020gallery\u0020alias",
            "url": "classes/App-Model-Entity-Gallery.html#method_setAlias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AsetTag\u0028\u0029",
            "name": "setTag",
            "summary": "Sets\u0020gallery\u0020tag",
            "url": "classes/App-Model-Entity-Gallery.html#method_setTag"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AsetUpdated\u0028\u0029",
            "name": "setUpdated",
            "summary": "Sets\u0020gallery\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-Gallery.html#method_setUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AsetState\u0028\u0029",
            "name": "setState",
            "summary": "Sets\u0020gallery\u0020state",
            "url": "classes/App-Model-Entity-Gallery.html#method_setState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Return\u0020gallery\u0020ID",
            "url": "classes/App-Model-Entity-Gallery.html#method_getId"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetImages\u0028\u0029",
            "name": "getImages",
            "summary": "Returns\u0020images\u0020associated\u0020to\u0020this\u0020gallery",
            "url": "classes/App-Model-Entity-Gallery.html#method_getImages"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetThumbnail\u0028\u0029",
            "name": "getThumbnail",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#method_getThumbnail"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Returns\u0020gallery\u0020title",
            "url": "classes/App-Model-Entity-Gallery.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Returns\u0020gallery\u0020description",
            "url": "classes/App-Model-Entity-Gallery.html#method_getDescription"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetAlias\u0028\u0029",
            "name": "getAlias",
            "summary": "Returns\u0020gallery\u0020alias",
            "url": "classes/App-Model-Entity-Gallery.html#method_getAlias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetTag\u0028\u0029",
            "name": "getTag",
            "summary": "Returns\u0020gallery\u0020tag",
            "url": "classes/App-Model-Entity-Gallery.html#method_getTag"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetUpdated\u0028\u0029",
            "name": "getUpdated",
            "summary": "Returns\u0020gallery\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-Gallery.html#method_getUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "Returns\u0020gallery\u0020state",
            "url": "classes/App-Model-Entity-Gallery.html#method_getState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_id"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_title"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_description"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024alias",
            "name": "alias",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_alias"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024images",
            "name": "images",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_images"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024tag",
            "name": "tag",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_tag"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024updated",
            "name": "updated",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_updated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Gallery\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/App-Model-Entity-Gallery.html#property_state"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image",
            "name": "Image",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AsetGallery\u0028\u0029",
            "name": "setGallery",
            "summary": "Sets\u0020image\u0020gallery",
            "url": "classes/App-Model-Entity-Image.html#method_setGallery"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020image\u0020title",
            "url": "classes/App-Model-Entity-Image.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AsetSource\u0028\u0029",
            "name": "setSource",
            "summary": "Sets\u0020source\u0020to\u0020image",
            "url": "classes/App-Model-Entity-Image.html#method_setSource"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AsetOrdering\u0028\u0029",
            "name": "setOrdering",
            "summary": "Sets\u0020image\u0020ordering",
            "url": "classes/App-Model-Entity-Image.html#method_setOrdering"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AsetUpdated\u0028\u0029",
            "name": "setUpdated",
            "summary": "Sets\u0020image\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-Image.html#method_setUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AsetState\u0028\u0029",
            "name": "setState",
            "summary": "Sets\u0020image\u0020state",
            "url": "classes/App-Model-Entity-Image.html#method_setState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Returns\u0020image\u0020ID",
            "url": "classes/App-Model-Entity-Image.html#method_getId"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetGallery\u0028\u0029",
            "name": "getGallery",
            "summary": "Returns\u0020image\u0020gallery",
            "url": "classes/App-Model-Entity-Image.html#method_getGallery"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Returns\u0020image\u0020title",
            "url": "classes/App-Model-Entity-Image.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetSource\u0028\u0029",
            "name": "getSource",
            "summary": "Returns\u0020image\u0020source",
            "url": "classes/App-Model-Entity-Image.html#method_getSource"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetOrdering\u0028\u0029",
            "name": "getOrdering",
            "summary": "Returns\u0020image\u0020ordering",
            "url": "classes/App-Model-Entity-Image.html#method_getOrdering"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetUpdated\u0028\u0029",
            "name": "getUpdated",
            "summary": "Returns\u0020image\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-Image.html#method_getUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "Returns\u0020image\u0020state",
            "url": "classes/App-Model-Entity-Image.html#method_getState"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_id"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024gallery",
            "name": "gallery",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_gallery"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_title"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024source",
            "name": "source",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_source"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024updated",
            "name": "updated",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_updated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024ordering",
            "name": "ordering",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_ordering"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Image\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/App-Model-Entity-Image.html#property_state"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag",
            "name": "Tag",
            "summary": "",
            "url": "classes/App-Model-Entity-Tag.html"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Model-Entity-Tag.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "Sets\u0020tag\u0020title",
            "url": "classes/App-Model-Entity-Tag.html#method_setTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Returns\u0020tag\u0020id",
            "url": "classes/App-Model-Entity-Tag.html#method_getId"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Returns\u0020tag\u0020title",
            "url": "classes/App-Model-Entity-Tag.html#method_getTitle"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Model-Entity-Tag.html#property_id"
        },                {
            "fqsen": "\\App\\Model\\Entity\\Tag\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/App-Model-Entity-Tag.html#property_title"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User",
            "name": "User",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#method___construct"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "Sets\u0020user\u0020username",
            "url": "classes/App-Model-Entity-User.html#method_setUsername"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "Sets\u0020user\u0020password",
            "url": "classes/App-Model-Entity-User.html#method_setPassword"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "Sets\u0020user\u0020e\u002Dmail",
            "url": "classes/App-Model-Entity-User.html#method_setEmail"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetName\u0028\u0029",
            "name": "setName",
            "summary": "Sets\u0020user\u0020name",
            "url": "classes/App-Model-Entity-User.html#method_setName"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetSurname\u0028\u0029",
            "name": "setSurname",
            "summary": "Sets\u0020user\u0020surname",
            "url": "classes/App-Model-Entity-User.html#method_setSurname"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetUpdated\u0028\u0029",
            "name": "setUpdated",
            "summary": "Sets\u0020user\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-User.html#method_setUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AsetAvatar\u0028\u0029",
            "name": "setAvatar",
            "summary": "Sets\u0020user\u0020avatar",
            "url": "classes/App-Model-Entity-User.html#method_setAvatar"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "Return\u0020user\u0020ID",
            "url": "classes/App-Model-Entity-User.html#method_getId"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "Returns\u0020user\u0020username",
            "url": "classes/App-Model-Entity-User.html#method_getUsername"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Returns\u0020user\u0020password",
            "url": "classes/App-Model-Entity-User.html#method_getPassword"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "Returns\u0020user\u0020e\u002Dmail",
            "url": "classes/App-Model-Entity-User.html#method_getEmail"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "Returns\u0020user\u0020name",
            "url": "classes/App-Model-Entity-User.html#method_getName"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetSurname\u0028\u0029",
            "name": "getSurname",
            "summary": "Returns\u0020user\u0020surname",
            "url": "classes/App-Model-Entity-User.html#method_getSurname"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetUpdated\u0028\u0029",
            "name": "getUpdated",
            "summary": "Returns\u0020user\u0020updated\u0020date",
            "url": "classes/App-Model-Entity-User.html#method_getUpdated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003AgetAvatar\u0028\u0029",
            "name": "getAvatar",
            "summary": "Returns\u0020user\u0020avatar",
            "url": "classes/App-Model-Entity-User.html#method_getAvatar"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_id"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_username"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_password"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_email"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_name"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024surname",
            "name": "surname",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_surname"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024updated",
            "name": "updated",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_updated"
        },                {
            "fqsen": "\\App\\Model\\Entity\\User\u003A\u003A\u0024avatar",
            "name": "avatar",
            "summary": "",
            "url": "classes/App-Model-Entity-User.html#property_avatar"
        },                {
            "fqsen": "\\App\\Model\\Fixtures\\UserLoader",
            "name": "UserLoader",
            "summary": "",
            "url": "classes/App-Model-Fixtures-UserLoader.html"
        },                {
            "fqsen": "\\App\\Model\\Fixtures\\UserLoader\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "",
            "url": "classes/App-Model-Fixtures-UserLoader.html#method_load"
        },                {
            "fqsen": "\\App\\View\\BaseView",
            "name": "BaseView",
            "summary": "",
            "url": "classes/App-View-BaseView.html"
        },                {
            "fqsen": "\\App\\View\\BaseView\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/App-View-BaseView.html#method___construct"
        },                {
            "fqsen": "\\App\\View\\BaseView\u003A\u003AsetResponseHeaders\u0028\u0029",
            "name": "setResponseHeaders",
            "summary": "Sets\u0020response\u0020headers\u0020by\u0020ini\u0020file",
            "url": "classes/App-View-BaseView.html#method_setResponseHeaders"
        },                {
            "fqsen": "\\App\\View\\Error",
            "name": "Error",
            "summary": "",
            "url": "classes/App-View-Error.html"
        },                {
            "fqsen": "\\App\\View\\Error\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Rednders\u0020error",
            "url": "classes/App-View-Error.html#method_render"
        },                {
            "fqsen": "\\App\\View\\Json",
            "name": "Json",
            "summary": "",
            "url": "classes/App-View-Json.html"
        },                {
            "fqsen": "\\App\\View\\Json\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "Displays\u0020data\u0020in\u0020JSON\u0020format",
            "url": "classes/App-View-Json.html#method_render"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/app-controller.html"
        },                {
            "fqsen": "\\App\\Lib\\Assert",
            "name": "Assert",
            "summary": "",
            "url": "namespaces/app-lib-assert.html"
        },                {
            "fqsen": "\\App\\Lib",
            "name": "Lib",
            "summary": "",
            "url": "namespaces/app-lib.html"
        },                {
            "fqsen": "\\App\\Lib\\Authorization",
            "name": "Authorization",
            "summary": "",
            "url": "namespaces/app-lib-authorization.html"
        },                {
            "fqsen": "\\App\\Lib\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/app-lib-command.html"
        },                {
            "fqsen": "\\App\\Lib\\Configuration",
            "name": "Configuration",
            "summary": "",
            "url": "namespaces/app-lib-configuration.html"
        },                {
            "fqsen": "\\App\\Lib\\FileSystem",
            "name": "FileSystem",
            "summary": "",
            "url": "namespaces/app-lib-filesystem.html"
        },                {
            "fqsen": "\\App\\Lib\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-lib-http.html"
        },                {
            "fqsen": "\\App\\Lib\\Mailer",
            "name": "Mailer",
            "summary": "",
            "url": "namespaces/app-lib-mailer.html"
        },                {
            "fqsen": "\\App\\Lib\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/app-lib-middleware.html"
        },                {
            "fqsen": "\\App\\Lib\\Security",
            "name": "Security",
            "summary": "",
            "url": "namespaces/app-lib-security.html"
        },                {
            "fqsen": "\\App\\Lib\\Util",
            "name": "Util",
            "summary": "",
            "url": "namespaces/app-lib-util.html"
        },                {
            "fqsen": "\\App\\Model\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "namespaces/app-model-entity.html"
        },                {
            "fqsen": "\\App\\Model",
            "name": "Model",
            "summary": "",
            "url": "namespaces/app-model.html"
        },                {
            "fqsen": "\\App\\Model\\Fixtures",
            "name": "Fixtures",
            "summary": "",
            "url": "namespaces/app-model-fixtures.html"
        },                {
            "fqsen": "\\App\\View",
            "name": "View",
            "summary": "",
            "url": "namespaces/app-view.html"
        }            ]
);
