name: Deploy

on:
  workflow_dispatch:
    inputs:
      instance:
        description: 'Instance'
        required: true

defaults:
  run:
   shell: bash -ieo pipefail {0}

jobs:
  tardis:
      runs-on: self-hosted
      steps:
        - name: Checkout
          working-directory: /var/www/${{ github.event.inputs.instance }}/web
          run: git pull origin master

        - name: Install
          working-directory: /var/www/${{ github.event.inputs.instance }}/web
          run: ./bin/install.sh ${{ secrets.DB_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }}
