name: Deploy

on:
  workflow_dispatch:
    inputs:
      instance:
        description: 'Instance'
        required: true

defaults:
  run:
   shell: bash -ieo pipefail {0}
   working-directory: /var/www/pc.stacha.dev/web

jobs:
  deploy:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v2
          with:
            ref: master
          
        - name: Install
          run: ./bin/install.sh ${{ secrets.DB_USER }} ${{ secrets.DB_PASSWORD }} ${{ secrets.DB_NAME }}
