name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: imagick, xdebug
        tools: composer:v2
    - uses: getong/mariadb-action@v1.1
      with:
        mysql database: 'test'
        mysql root password: 'password'

    - name: Install new instance
      run: ./bin/install.sh root password test 127.0.0.1 3306

    - name: Validate DB schema
      run: composer orm:validate

    - name: Coding Standards
      run: composer cs

    - name: Static Analysis
      run: composer phpstan

    - name: Unit tests
      run: composer test